### PR TITLE
Update to latest upstream

### PR DESCRIPTION
**Pull request by Oizaro**

### CODE REVIEW

**Comment by chirayudesai** [comment]
Hi there,

You'll want to add in something like:

4278: login: Switch to SettingsProvider for "Alt Sign in" | https://review.calyxos.org/c/CalyxOS/platform_external_microg_GmsCore/+/4278

to have the spoofing code work well with the SettingsProvider refactor.

**Comment by Oizaro** [comment]
> Hi there,
> 
> You'll want to add in something like:
> 
> 4278: login: Switch to SettingsProvider for "Alt Sign in" | https://review.calyxos.org/c/CalyxOS/platform_external_microg_GmsCore/+/4278
> 
> to have the spoofing code work well with the SettingsProvider refactor.

Should be already done in the current code, with the same previous (re-adapted) code.

**Comment by chirayudesai** [comment]
> > Hi there,
> > You'll want to add in something like:
> > 4278: login: Switch to SettingsProvider for "Alt Sign in" | https://review.calyxos.org/c/CalyxOS/platform_external_microg_GmsCore/+/4278
> > to have the spoofing code work well with the SettingsProvider refactor.
> 
> Should be already done in the current code, with the same previous (re-adapted) code.

I don't see it at https://github.com/YTVanced/VancedMicroG/blob/4c9230d27994711465425d6942e3bf9419d9f182/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L166

It's still calling `getDefaultSharedPreferences` directly, which should not be done.

**Comment by Oizaro** [comment]
> > > Hi there,
> > > You'll want to add in something like:
> > > 4278: login: Switch to SettingsProvider for "Alt Sign in" | https://review.calyxos.org/c/CalyxOS/platform_external_microg_GmsCore/+/4278
> > > to have the spoofing code work well with the SettingsProvider refactor.
> > 
> > 
> > Should be already done in the current code, with the same previous (re-adapted) code.
> 
> I don't see it at
> 
> https://github.com/YTVanced/VancedMicroG/blob/4c9230d27994711465425d6942e3bf9419d9f182/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L166
> 
> It's still calling `getDefaultSharedPreferences` directly, which should not be done.

This is the code to hide microg icon from launcher. I don't know if it's the case of change it.

**Comment by chirayudesai** [comment]
> > > > Hi there,
> > > > You'll want to add in something like:
> > > > 4278: login: Switch to SettingsProvider for "Alt Sign in" | https://review.calyxos.org/c/CalyxOS/platform_external_microg_GmsCore/+/4278
> > > > to have the spoofing code work well with the SettingsProvider refactor.
> > > 
> > > 
> > > Should be already done in the current code, with the same previous (re-adapted) code.
> > 
> > 
> > I don't see it at
> > https://github.com/YTVanced/VancedMicroG/blob/4c9230d27994711465425d6942e3bf9419d9f182/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L166
> > 
> > It's still calling `getDefaultSharedPreferences` directly, which should not be done.
> 
> This is the code to hide microg icon from launcher. I don't know if it's the case of change it.

What happened was calling `getDefaultSharedPreferences` from everywhere would override settings.

So we changed it in microG to use SettingsProvider. So this should be changed here too - both the hide launcher icon part, and also the lines below it, which I covered in my linked patch.

https://github.com/YTVanced/VancedMicroG/blob/4c9230d27994711465425d6942e3bf9419d9f182/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L169-L173

This should all be changed to use SettingsProvider to make sure it doesn't get overriden when something else writes to it.

My commit handles this for the Huawei button, but we don't have hide launcher icon. See https://github.com/CalyxOS/platform_external_microg_GmsCore/commit/a68d262abd36a33c2aa88c69aad5b143fc251ceb

**Comment by Oizaro** [comment]
> > > > > Hi there,
> > > > > You'll want to add in something like:
> > > > > 4278: login: Switch to SettingsProvider for "Alt Sign in" | https://review.calyxos.org/c/CalyxOS/platform_external_microg_GmsCore/+/4278
> > > > > to have the spoofing code work well with the SettingsProvider refactor.
> > > > 
> > > > 
> > > > Should be already done in the current code, with the same previous (re-adapted) code.
> > > 
> > > 
> > > I don't see it at
> > > https://github.com/YTVanced/VancedMicroG/blob/4c9230d27994711465425d6942e3bf9419d9f182/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L166
> > > 
> > > It's still calling `getDefaultSharedPreferences` directly, which should not be done.
> > 
> > 
> > This is the code to hide microg icon from launcher. I don't know if it's the case of change it.
> 
> What happened was calling `getDefaultSharedPreferences` from everywhere would override settings.
> 
> So we changed it in microG to use SettingsProvider. So this should be changed here too - both the hide launcher icon part, and also the lines below it, which I covered in my linked patch.
> 
> https://github.com/YTVanced/VancedMicroG/blob/4c9230d27994711465425d6942e3bf9419d9f182/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L169-L173
> 
> This should all be changed to use SettingsProvider to make sure it doesn't get overriden when something else writes to it.
> 
> My commit handles this for the Huawei button, but we don't have hide launcher icon. See [CalyxOS/platform_external_microg_GmsCore@a68d262](https://github.com/CalyxOS/platform_external_microg_GmsCore/commit/a68d262abd36a33c2aa88c69aad5b143fc251ceb)

We use another approach to Huawei spoofing (without a preference on settings page, from what you can see), so at the moment we just need this improvement for microg hide icon.

Can you provide it?

**Comment by Oizaro** [comment]
> > > > > Hi there,
> > > > > You'll want to add in something like:
> > > > > 4278: login: Switch to SettingsProvider for "Alt Sign in" | https://review.calyxos.org/c/CalyxOS/platform_external_microg_GmsCore/+/4278
> > > > > to have the spoofing code work well with the SettingsProvider refactor.
> > > > 
> > > > 
> > > > Should be already done in the current code, with the same previous (re-adapted) code.
> > > 
> > > 
> > > I don't see it at
> > > https://github.com/YTVanced/VancedMicroG/blob/4c9230d27994711465425d6942e3bf9419d9f182/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L166
> > > 
> > > It's still calling `getDefaultSharedPreferences` directly, which should not be done.
> > 
> > 
> > This is the code to hide microg icon from launcher. I don't know if it's the case of change it.
> 
> What happened was calling `getDefaultSharedPreferences` from everywhere would override settings.
> 
> So we changed it in microG to use SettingsProvider. So this should be changed here too - both the hide launcher icon part, and also the lines below it, which I covered in my linked patch.
> 
> https://github.com/YTVanced/VancedMicroG/blob/4c9230d27994711465425d6942e3bf9419d9f182/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L169-L173
> 
> This should all be changed to use SettingsProvider to make sure it doesn't get overriden when something else writes to it.
> 
> My commit handles this for the Huawei button, but we don't have hide launcher icon. See [CalyxOS/platform_external_microg_GmsCore@a68d262](https://github.com/CalyxOS/platform_external_microg_GmsCore/commit/a68d262abd36a33c2aa88c69aad5b143fc251ceb)

Sorry for the previous (nonsense) message.

I'll merge your code soon.

**Comment by chirayudesai** [comment]
> Sorry for the previous (nonsense) message.
> 
> I'll merge your code soon.

No worries, and to be clear we're using the exact same mechanism for `brandSpoof`, it's an extra button on the login screen.
> 
> P.S: Same thing should eventually be done with others preferences?

Yeah. it is done with all upstream preferences, but if you have added anything you should switch them all over.

See https://github.com/YTVanced/VancedMicroG/pull/152/commits/aa3a2d65cda328717ac75626d3466b37482e8d4c (and ofc my commit) for some examples.

**Comment by Oizaro** [comment]
> > Sorry for the previous (nonsense) message.
> > I'll merge your code soon.
> 
> No worries, and to be clear we're using the exact same mechanism for `brandSpoof`, it's an extra button on the login screen.

Yeah...I thought you followed another way.

In every case I'm currently working on hide microg icon switch and the one about duplication cast.

**Pull request merged**
