### PR TITLE
MicroG 0.2.23.220217

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by KevinX8** [comment]
@Oizaro it doesn't build still

**Comment by Oizaro** [comment]
> @Oizaro it doesn't build still

It build on AS. I'll fix GitHub action build asap.

**Comment by KevinX8** [comment]
> > @Oizaro it doesn't build still
> 
> It build on AS. I'll fix GitHub action build asap.

It doesn't build in AS for me idk

**Comment by Oizaro** [comment]
> > > @Oizaro it doesn't build still
> > 
> > 
> > It build on AS. I'll fix GitHub action build asap.
> 
> It doesn't build in AS for me idk

Ok...I tried and also in my case the error appears. In practice AS has mistakenly removed two references to libraries it considered unused (for no apparent reason). This obviously happened after trying the apk and cleaning up the unused references.

**Comment by Oizaro** [comment]
> Ok...I tried to build the project and error appeared in my case too. In practice AS has mistakenly removed two libraries references it considered unused (for no apparent reason). This obviously happened after I tried apk...and cleaning up the unused references.

Ok...I tried to build the project and error appeared in my case too. In practice AS has mistakenly removed two libraries references it considered unused (for no apparent reason). This obviously happened after I tried apk...and cleaning up the unused references.

**Comment by Oizaro** [comment]
@KevinX8 Everything is ready.

**Comment by Oizaro** [comment]
@KevinX8 Everything is ready now, I guess.

**Comment by Rafsanrafi1794** [comment]
Accept me

**Comment by Rafsanrafi1794** [comment]
###  @Aaaaa__

**Pull request merged**
